# Generated by Django 3.1 on 2020-09-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='either',
            name='topic',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
